"""Upgrade url

Revision ID: 35a884279db8
Revises: 47b9346ceb6e
Create Date: 2024-06-30 19:39:47.849635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a884279db8'
down_revision: Union[str, None] = '47b9346ceb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp', 'test')
    # ### end Alembic commands ###
